### ISSUE TITLE
Need a web.config file to point IIS into the public folder as root

### ISSUE THREAD

**Issue by aarongustafson** [markhuot/cards#1]
I don’t have a template, but the sample here may work: http://blog.qbotx.com/basic-laravel-5-on-microsoft-azure-part-1/

**Comment by markhuot** [comment]
Helpful, thanks. I'll get this implemented.

**Comment by aarongustafson** [comment]
::Bump::

It’s the last day of the contest.

**Comment by markhuot** [comment]
![movies_movies_h_home_alone_010009_](https://cloud.githubusercontent.com/assets/48975/19003938/1ef0c09a-8721-11e6-934c-01ae550796fd.jpg)

In there now, sorry Aaron!
